# Generated by Django 3.2.5 on 2022-06-24 06:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.Profile.upload_design_to),
        ),
    ]
