# Generated by Django 3.2.5 on 2022-06-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20220624_1134'),
        ('accounts', '0029_alter_profile_profile_picture'),
    ]

    operations = [
    ]
