# Generated by Django 3.2.5 on 2022-06-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_auto_20220615_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(choices=[('option_a', 'option_a'), ('option_b', 'option_b'), ('option_d', 'option_d'), ('option_c', 'option_c')], default='option_a', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='cognitive_level',
            field=models.CharField(choices=[('Comprehension', 'Comprehension'), ('Application', 'Application'), ('Knowledge', 'Knowledge')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Easy', 'Easy'), ('Hard', 'Hard')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Match_the_following', 'Match_the_following'), ('MCQ', 'MCQ'), ('Fill_in_the_blanks', 'Fill_in_the_blanks')], default='0', max_length=20),
        ),
    ]
