# Generated by Django 3.2.5 on 2022-06-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_auto_20220615_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(choices=[('option_a', 'option_a'), ('option_b', 'option_b'), ('option_c', 'option_c'), ('option_d', 'option_d')], default='option_a', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='cognitive_level',
            field=models.CharField(choices=[('Application', 'Application'), ('Comprehension', 'Comprehension'), ('Knowledge', 'Knowledge')], default='0', max_length=20),
        ),
    ]
