# Generated by Django 3.2.5 on 2022-06-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_auto_20220615_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_paper',
            name='no_of_questions',
            field=models.ManyToManyField(to='academics.Question'),
        ),
    ]
