# Generated by Django 3.2.5 on 2022-07-15 07:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_auto_20220713_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_no',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.chapter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.grade'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.grade'),
        ),
        migrations.AlterField(
            model_name='question_paper',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.grade'),
        ),
    ]
