# Generated by Django 3.2.5 on 2022-07-19 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0023_auto_20220715_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField()),
                ('remarks', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=50)),
                ('created_staff_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.grade')),
                ('question_paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.question_paper')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50)),
                ('score', models.PositiveIntegerField()),
                ('question_paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.question_paper')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academics.test')),
            ],
        ),
    ]
